### ISSUE TITLE
4/9 회의록

### ISSUE THREAD

**Issue by jiyeonyh** [team-lupin/plan#13]
## 회의 일시 / 방식 / 진행자 / 참여 인원
- 회의 일시 : 2023년 4월 1일 
- 회의 방식 : 온라인 (디스코드)
- 진행자 : 김병국 > 이은송 > 윤종엽 > `정지연`
- 참여 인원 : 김병국, 이은송, 정지연

---
### 지난주 논의
- 회의에서 정해진 사항들 wiki로 관리
  ex. 개발 스택, 브랜치 전략 등
#### 김병국
- spring boot 3.0.4 / JDK17 / kotlin / JPA (QueryDSL)
- 개발 DB (MariaDB) 환경 설정 진행중 (ssh 터널링)
#### 윤종엽
- 불참
#### 이은송
- 패스
#### 정지연
- 환경설정 (babel / recoil 등) -> 에러 해결중

### 추가 논의
- 온라인으로 할 때 회의 전 켜놓고 개발 하기

### 추후 논의

---

### 김병국 
- DB연결해보고 잘 되면 테이블 생성
### 이은송
- DB설계한거 기반으로 화면 설계
### 정지연
- 상세페이지 화면 개발

---

## 다음 회의 날짜 / 시간
- 회의 방식 : 오프라인
- 회의 날짜 : 2023년 4월 29일 
- 회의 시간 : 오후 4시
- 회의 장소 : 사당역 스터디위드
- 회의 진행자 : 윤종엽

**Comment by gambit133** [comment]
https://dbdiagram.io/d/6427064f5758ac5f1725cf45
